if has("gui_macvim")
	"let &t_SI.="\e[6 q" 
	"let &t_SR.="\e[4 q" 
	"let &t_EI.="\e[2 q" 
	"add NODE path	
	highlight Comment ctermfg=green
endif
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'jiangmiao/auto-pairs'
"Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'itchyny/landscape.vim'
call plug#end()	

"settings
syntax on
set ruler
set number
"set number relativenumber

set noexpandtab
set tabstop=4
set shiftwidth=0
set noswapfile
"set noshowmode
set title
set cmdheight=1
"set laststatus=2
set signcolumn=yes
set showcmd
set hlsearch
set incsearch
set cursorline
set ai
set cin

set wrap linebreak nolist
set textwidth=80

set t_Co=256

"USE HJKL MORON!!!
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

colorscheme landscape 

"ColorColumn
"set colorcolumn=80
"highlight ColorColumn ctermbg=darkgray

"lightline
"let g:lightline = {
"      \ 'colorscheme': 'landscape'
"      \ }

"mappings
map <C-n> :NERDTreeToggle<CR>
inoremap <C-j> <down>
inoremap <C-k> <up>
