source $HOME/htmlgod/workspace/scripts/activate
alias ls='ls -G'
alias tree='tree -C'
autoload -Uz compinit promptinit
compinit
promptinit

prompt walters

export CLICOLOR=1
export LSCOLORS=gafacadabaegedabagacad

